sheet: Obial
map:
  ID_REGISTRO: ID_REGISTRO
  TITULO_CURTO: TITULO_CURTO
  DATA_INICIO: DATA_INICIO
  DATA_FIM: DATA_FIM
  PAIS: PAIS
  UF_DEPTO: UF_DEPTO
  MUNICIPIO_PROVINCIA: MUNICIPIO_PROVINCIA
  RECORTE_TERRITORIAL: RECORTE_TERRITORIAL
  POVO_NACAO: POVO_NACAO
  ORGANIZACAO_INDIGENA: ORGANIZACAO_INDIGENA
  ESTRATEGIA_ARVORE_PRIMARIA: ESTRATEGIA_ARVORE_PRIMARIA
  ACAO_MATRIZ: ACAO_MATRIZ
  CHECK_ESTRAT_MATRIZ: CHECK_ESTRAT_MATRIZ
  ACAO_DERIVADA: ACAO_DERIVADA
  PAUTA_REIVINDICATIVA: PAUTA_REIVINDICATIVA
  RELACOES_HETERONOMAS: RELACOES_HETERONOMAS
  ESCALA: ESCALA
  RAIZ_1: RAIZ_1
  RAIZ_2: RAIZ_2
  AGENTE_CONTRAPOSTO: AGENTE_CONTRAPOSTO
  TERRITORIO_EM_DISPUTA: TERRITORIO_EM_DISPUTA
  OBJETO_ESPACIAL_PRODUZIDO: OBJETO_ESPACIAL_PRODUZIDO
  DESCRICAO_OBJETO: DESCRICAO_OBJETO
  TIPO_FONTE: TIPO_FONTE
  REFERENCIA_URL: REFERENCIA_URL
  NIVEL_EVIDENCIA: NIVEL_EVIDENCIA
  STATUS_VALIDACAO: STATUS_VALIDACAO
  DESFECHO: DESFECHO
  NIVEL_ESCALA_PUBLICAVEL: NIVEL_ESCALA_PUBLICAVEL
  RISCO_PUBLICACAO: RISCO_PUBLICACAO
  GEO_PRECISA: GEO_PRECISA
  COORD_LAT: COORD_LAT
  COORD_LON: COORD_LON
  NOTA_ANALITICA: NOTA_ANALITICA
  CODIFICADOR: CODIFICADOR
  DATA_VALIDACAO: DATA_VALIDACAO
  VALIDACAO_HUMANA: VALIDACAO_HUMANA
  COMENTARIO_HUMANO: COMENTARIO_HUMANO
